### ISSUE TITLE
"Create Partial From Selection" Error

### ISSUE THREAD

**Issue by manewitz** [drnic/ruby-on-rails-tmbundle#38]
I'm on OS 10.6.6/TextMate 1.5.10/Ruby 1.9.2/Rails 3.0.6 with RVM. Instead of the desired output, it drops the following:

```
/Applications/TextMate.app/Contents/SharedSupport/Support/lib/ui.rb:355:in `to_plist': An object in the argument tree could not be converted (ArgumentError)
from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/ui.rb:355:in `request_string_core'
from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/ui.rb:193:in `request_string'
from /Users/mike/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:23:in `<main>'
```

I'll report back any findings if I can figure it out.

Thanks!

**Comment by mhenrixon** [comment]
I recommend you have a look https://github.com/TechnoGate/ruby-on-rails-tmbundle instead we fixed a lot of small issues though the problem you are experiencing is because your plists are not updated for ruby 1.9.2.

Follow these steps to make it work.

 git clone git://github.com/kballard/osx-plist.git
 cd osx-plist/ext/plist
 ruby extconf.rb && make
 cp plist.bundle /Applications/TextMate.app/Contents/SharedSupport/Support/lib/osx/

**Comment by manewitz** [comment]
thanks, that totally fixed it
